name: Mortgage Rate Check

on:
  schedule:
    - cron: '0 14 * * 4'  # Every Thursday at 9 AM ET (14:00 UTC)
  workflow_dispatch:

jobs:
  check-rate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run rate check
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python mortgage_checker.py
